# Generated by Django 5.1 on 2024-08-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="hit",
            field=models.IntegerField(default=0),
        ),
    ]
