# Generated by Django 5.1 on 2024-08-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_remove_post_img_upload_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
